spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dms_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:sasql}
    initialization-mode: always
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dms_db}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:sasql}
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
  graphql:
    graphiql:
      enabled: true
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    org.springframework.security: TRACE
    # io.r2dbc.postgresql.PARAM: DEBUG # for parameters

openfilz:
  calculate-checksum: true
  full-text:
    active: true
    indexation-mode: local # local (only choice for the moment) -> to be developed : redis | kafka | nats
    opensearch:
      host: localhost
      port: 9200
      scheme: https
      username: admin
      password: yourStrongPassword123!
  security:
    no-auth: true
    worm-mode: false
    cors-allowed-origins: http://localhost:4200, http://localhost:4900 # Comma-separated list of authorized origins
